### ISSUE TITLE
Cannot build project tests

### ISSUE THREAD

**Issue by pierre-24** [grimme-lab/xtb#237]
**Describe the bug**
When building the project with intel 2018 and `-Dstatic=false` (you know I cannot do without it), the tests cannot build due to an error:

```
icc  -o TESTSUITE/xtb_test 'TESTSUITE/477912c@@xtb_test@exe/tests_peeq.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/assertion.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/tbdef_molecule.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/tbdef_wsc.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/geometry_reader.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/eeq_model.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/pbc_tools.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/dftd4.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/gfn2.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/gfn1.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/gfn0.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/peeq.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/symmetry.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/thermo.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/tbdef_atomlist.f90.o' -Wl,--as-needed -Wl,--no-undefined -qopenmp -Wl,--start-group libxtb.a -lmkl_rt -pthread '-Wl,-rpath,$ORIGIN/..' -Wl,-rpath-link,/home/pbeaujea/xtb/build/ -lifcore -limf -Wl,--end-group
/lib/../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
[357/359] Compiling Fortran object 'xtb@exe/src_prog_main.f90.o'
../src/prog/main.f90(18): (col. 9) remark: MAIN__ has been targeted for automatic cpu dispatch
ninja: build stopped: subcommand failed.
```

**To Reproduce**

I used the "standard" build procedure, thus

```
export FC=ifort CC=icc
meson setup build --optimization 2 -Dstatic=false
ninja -C build test
```

Which was working with version 6.2.2 (it is not with later version, tested 6.2.3 and 6.3.0)

**Expected behaviour**
building correctly.

**Additional context**

That is the same issue as #1 ... But that was working with version 6.2.2 (see #40). You modified the `meson.build` since, so that may be the issue (or not).

**Comment by awvwgk** [comment]
You are lucky, Pierre. I just merged the fix for your issue half an hour ago (f8a84e0), at least I hope so.

**Comment by pierre-24** [comment]
Indeed it works better .... But.

I end up with strange errors, [see there](https://gist.github.com/pierre-24/e191bf500e057214084a2007ad287260):

```
--- stderr ---
/home/pbeaujea/xtb/build/TESTSUITE/xtb_test: symbol lookup error: /opt/cecisw/arch/easybuild/2018b/software/imkl/2018.3.222-iimpi-2018b/mkl/lib/intel64/libmkl_core.so: undefined symbol: log
-------
```

It only happens on a few tests, thought, but it is quite strange (again, same compilation procedure as above)

**Comment by awvwgk** [comment]
Looks like the executable with shared dependencies is short a few libraries.

Generally we should find something like:

```
> ldd build_shared/libxtb.so
	linux-vdso.so.1 (0x00007ffc5b94c000)
	libmkl_rt.so => /opt/intel2019/compilers_and_libraries_2019.3.199/linux/mkl/lib/intel64_lin/libmkl_rt.so (0x00007ffb2ba88000)
	libifcore.so.5 => /opt/intel2019/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64_lin/libifcore.so.5 (0x00007ffb2b72b000)
	libimf.so => /opt/intel2019/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64_lin/libimf.so (0x00007ffb2b18b000)
	libsvml.so => /opt/intel2019/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64_lin/libsvml.so (0x00007ffb29773000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007ffb296fd000)
	libintlc.so.5 => /opt/intel2019/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x00007ffb2948b000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007ffb29469000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007ffb292a3000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007ffb2929e000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007ffb29158000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007ffb30002000)
```

But the produced executable is missing the Fortran runtime libraries, for whatever reason:

```
> ldd build_shared/xtb      
	linux-vdso.so.1 (0x00007ffcd17b8000)
	libmkl_rt.so => /opt/intel2019/compilers_and_libraries_2019.3.199/linux/mkl/lib/intel64_lin/libmkl_rt.so (0x00007fa499224000)
	libiomp5.so => /opt/intel2019/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64_lin/libiomp5.so (0x00007fa498e2f000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fa498db1000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fa498beb000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fa498be4000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fa498bca000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fa49990e000)
```

The Fortran runtime library (`ifcore`) is not specified at any point in the meson.build and it shouldn't, because the linker should be able to figure it out on its own.

One thing that fixes this is hacking in the `-mkl=parallel` option by adding `-Dfortran_args="-mkl=parallel"` and/or `-Dfortran_link_args="-mkl=parallel"` in the configuration step, which defeats the purpose of dynamic linking again by not linking against the real time MKL but the shared MKL (meaning it will work on your machine and only your machine).

The obvious thing to do for `-Dstatic=false` would be to link against the `libxtb.so`, which will work certainly work for you, but break the `xtb` build for everybody else.

```patch
diff --git a/TESTSUITE/meson.build b/TESTSUITE/meson.build
index cd6df03..dcb2cb8 100644
--- a/TESTSUITE/meson.build
+++ b/TESTSUITE/meson.build
@@ -43,7 +43,8 @@ xtb_test = files(
 xtb_test = executable(
   'xtb_test',
   sources: xtb_test,
-  dependencies: xtb_dep_static,
+  dependencies: xtb_dep,
+  include_directories: xtb_common.private_dir_include(),
   link_language: 'fortran',
 )
 
diff --git a/meson.build b/meson.build
index bd1913e..eb56ec8 100644
--- a/meson.build
+++ b/meson.build
@@ -131,7 +131,8 @@ endif
 xtb_exe = executable(
   meson.project_name(),
   sources: prog,
-  dependencies: xtb_dep_static,
+  dependencies: xtb_dep,
+  include_directories: xtb_common.private_dir_include(),
   link_language: 'fortran',
   install: install,
 )
```

Unfortunately, we cannot mask the fact, that compiling modern Fortran code does not work without direct access to the generated module files (hacky `private_dir_include`) and this setup is likely to break due to ABI incompatibilities between the binary and the shared object, which makes things worse.

I guess, I have to devote again a bit of time on this issue to figure out a stable way to work in every possible setup.

**Comment by awvwgk** [comment]
Maybe something that could work for you is using the MKL provided on conda-forge. The trick would be that you can link against conda-forges MKL with `-Dla_backend=netlib` and can avoid the hassle with all the different ways of linking MKL entirely. Didn't tried it with Intel so far but it works perfectly with GCC.

**Comment by pierre-24** [comment]
> [...] which defeats the purpose of dynamic linking again by not linking against the real time MKL but the shared MKL (meaning it will work on your machine and only your machine).

I don't get it. Since my purpose is to build a `xtb` executable for "my" machine (actually the supercomputer of my university, but that's the same), what would be the issue here (we can always play with `if get_option('static')` to avoid breaking the static build ?) 

I did get why the other proposition is not a good one, on the other hand (but if that's the only solution, I'll make a patch for my own compilation ;) )

------

> Maybe something that could work for you is using the MKL provided on conda-forge. 

Being on a supercomputer using EasyBuild (and many layers of dependencies), I would rather avoid depending on such a heavy (bloated?) thing like conda ^^ (`conda` and me are not friend, but that's my opinion)

**Comment by awvwgk** [comment]
> I don't get it. Since my purpose is to build a `xtb` executable for "my" machine (actually the supercomputer of my university, but that's the same), what would be the issue here (we can always play with `if get_option('static')` to avoid breaking the static build ?)

So far this was causing issues when the CPU functionalities differs between the build and the host machine, if the CPUs match then everything is fine. I tried on our cluster here which has different CPU generations and vendors, depending on which node the binary was linked against the shared MKL it does not work on other nodes, the real time MKL works fine everywhere.

Guarding with `if get_option('static')` is a possibility, but makes really messy and bloated meson.build files and I want to keep the logic around the MKL linking as confined as possible.

_______

Another option you might try is to replace the `-static` with `-static-intel` which should only link the Intel provided libraries statically and everything else dynamically.

**Comment by pierre-24** [comment]
> So far this was causing issues when the CPU functionalities differs between the build and the host machine, if the CPUs match then everything is fine. I tried on our cluster here which has different CPU generations and vendors, depending on which node the binary was linked against the shared MKL it does not work on other nodes, the real time MKL works fine everywhere.

Ah! Good that you mention that, because that is exactly what I'm trying to achieve :-) (we have intel and AMD CPUs here and it is already something to explain that to the intel compiler ... At least for the 2018 version)

I'll try the `-static-intel` option tomorow, then.

**Comment by awvwgk** [comment]
Maybe the best way of doing this is to get rid of `-Dstatic=<bool>` entirely and force to put it in with `-Dfortran_link_args=-static` in the configuration step.

I think #241 should address this issue by adding the `mkl-rt` option, which will take care of the missing `ifcore` dependency as well.
