### PR TITLE
Separate logic for MKL linking from static option

### LINKED ISSUE #237: Cannot build project tests
**Describe the bug**
When building the project with intel 2018 and `-Dstatic=false` (you know I cannot do without it), the tests cannot build due to an error:

```
icc  -o TESTSUITE/xtb_test 'TESTSUITE/477912c@@xtb_test@exe/tests_peeq.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/assertion.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/tbdef_molecule.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/tbdef_wsc.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/geometry_reader.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/eeq_model.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/pbc_tools.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/dftd4.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/gfn2.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/gfn1.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/gfn0.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/peeq.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/symmetry.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/thermo.f90.o' 'TESTSUITE/477912c@@xtb_test@exe/tbdef_atomlist.f90.o' -Wl,--as-needed -Wl,--no-undefined -qopenmp -Wl,--start-group libxtb.a -lmkl_rt -pthread '-Wl,-rpath,$ORIGIN/..' -Wl,-rpath-link,/home/pbeaujea/xtb/build/ -lifcore -limf -Wl,--end-group
/lib/../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
[357/359] Compiling Fortran object 'xtb@exe/src_prog_main.f90.o'
../src/prog/main.f90(18): (col. 9) remark: MAIN__ has been targeted for automatic cpu dispatch
ninja: build stopped: subcommand failed.
```

**To Reproduce**

I used the "standard" build procedure, thus

```
export FC=ifort CC=icc
meson setup build --optimization 2 -Dstatic=false
ninja -C build test
```

Which was working with version 6.2.2 (it is not with later version, tested 6.2.3 and 6.3.0)

**Expected behaviour**
building correctly.

**Additional context**

That is the same issue as #1 ... But that was working with version 6.2.2 (see #40). You modified the `meson.build` since, so that may be the issue (or not).

### PR DESCRIPTION
**Pull request by awvwgk**
Deletes the `-Dstatic` option, separates `mkl`, `mkl-static` (default) and `mkl-rt` as linear algebra backends.

`la_backend` | Description
--- | ---
`mkl` | link shared MKL libraries, produce dynamically linked binaries
`mkl-static` | link static MKL libraries, produce statically linked binaries
`mkl-rt` | link real time MKL library, produce dynamically linked binaries

*Precompiled binaries will be provided with Intel 17 and `mkl-static`.*

`mkl-static` is included for convenience and because it is the default for distribution of `xtb`. 
Following setup is equivalent to `mkl-static`:

```
meson setup build -Dla_backend=mkl -Dfortran_link_args=-static
```

To link static binaries with other backends the `-Dfortran_link_args=-static` flag should be provided in the configuration step.

Fixes #237

### CODE REVIEW

**Comment by pierre-24** [comment]
... `-Dla_backend=mkl` works for me <3

**Comment by pierre-24** [comment]
(didn't you forget to upgrade the documentation, or is it going in the RDT one ?)

**Comment by awvwgk** [comment]
The static flag was a hidden feature for you so far. But the in detail description of all the possibilities to link the MKL will go to RTD rather than the meson guide here.
